# Generated by Django 2.1.4 on 2019-01-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('job_role', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=50)),
                ('local_address', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
